IssueTracker.Web/Controllers/IssueController.cs
using IssueTracker.Web.Data;
using IssueTracker.Web.Domain;
using IssueTracker.Web.Filters;
using IssueTracker.Web.Infrastructure;
using IssueTracker.Web.Models.Issue;
using System;
using System.Linq;
using System.Web.Mvc;

namespace IssueTracker.Web.Controllers
{
    public class IssueController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICurrentUser _currentUser;

        public IssueController(ApplicationDbContext context, ICurrentUser currentUser)
        {
            _context = context;
            _currentUser = currentUser;
        }

        [ChildActionOnly]
        public ActionResult IssueWidget()
        {
            //return Content("Here's where issues would go!");
            var models = from i in _context.Issues
                select new IssueSummaryViewModel
                {
                    IssueID = i.IssueID,
                    Subject = i.Subject,
                    CreatedAt = i.CreatedAt
                };
            return PartialView(models.ToArray());
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken, Log("Created issue")]
        public ActionResult New(NewIssueForm form)
        {
            //var userId = User.Identity.GetUserId();
            //var user = _context.Users.Find(userId);
            _context.Issues.Add(new Issue(_currentUser.User, null, form.IssueType, form.Subject, form.Body));
            //_context.Logs.Add(new LogAction(user, "New", "Issue", "Created issue"));
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [Log("Viewed issue {id}")]
        public ActionResult View(int id)
        {
            var issue = _context.Issues.Find(id);
            if (issue == null)
            {
                throw new ApplicationException("Issue not found!");
            }

            //var userId = User.Identity.GetUserId();
            //var user = _context.Users.Find(userId);
            //_context.Logs.Add(new LogAction(user, "View", "Issue", "Viewed issue " + id));
            //_context.SaveChanges();

            var result = View(new IssueDetailsViewModel
            {
                IssueID = issue.IssueID,
                Subject = issue.Subject,
                CreatedAt = issue.CreatedAt,
                Body = issue.Body
            });

            return result;
        }

        [HttpPost, ValidateAntiForgeryToken,Log("Deleted issue {id}")]
        public ActionResult Delete(int id)
        {
            var issue = _context.Issues.Find(id);

            if (issue == null)
            {
                throw new ApplicationException("Issue not found!");
            }
            
            _context.Issues.Remove(issue);

            //var userId = User.Identity.GetUserId();
            //var user = _context.Users.Find(userId);
            //_context.Logs.Add(new LogAction(user, "Delete", "Issue", "Deleted issue " + id));
            //_context.SaveChanges();

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

IssueTracker.Web/Views/Shared/_Alerts.cshtml
@*@using IssueTracker.Web.Infrastructure.Alerts
@if (TempData.GetAlerts().Any())*@

IssueTracker.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Issue Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Issue Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Issue", "New", "Issue")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Issue Tracker</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")
    @Html.Partial("_Alerts")
    @RenderSection("scripts", required: false)
</body>
</html>